CREATE TABLE [dbo].[Rent]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NULL,
    [Month] INT NOT NULL, 
    [Year] INT NOT NULL, 
    [Amount] SMALLMONEY NOT NULL DEFAULT 0, 
    [Percentage] DECIMAL(5, 2) NOT NULL DEFAULT 52, 
    [Closed] BIT NOT NULL DEFAULT 0, 
    [Deleted] BIT NOT NULL DEFAULT 0, 
    [Timestamp] DATETIME2 NULL DEFAULT GETUTCDATE()
)
